import java.util.Scanner;
public class TestaPessoa {
    public static void main(String[] args){
        Scanner sc = new Scanner(System.in);
        Aluno a1 = new Aluno();
        Funcionario f1 = new Funcionario();
        Professor p1 = new Professor();
        Professor p2 = new Professor();
        a1.setNome("Lucas");
        a1.setIdade(20);
        a1.setSexo("Masculino");
        a1.Baderna();
        System.out.println(a1.getNome());
        System.out.println(a1.getIdade());
        a1.setMatricula("123723642194-2319");
        a1.setCurso("Sistemas de Informacao");
        System.out.println(a1.getMatricula());
        System.out.println(a1.getCurso());
        System.out.println(p1.getSexo());
        a1.fazerAniv();
        f1.setNome("luiza");
        f1.setIdade(32);
        f1.setTrabalhando(true);
        f1.setSetor("TI");
        f1.Trabson();
        f1.setSexo("Feminino");
        System.out.println(f1.getNome());
        System.out.println(f1.getIdade());
        System.out.println(f1.getSetor());
        System.out.println(p1.getSexo());
        f1.fazerAniv();
        f1.Trabalhar();
        p1.setNome("Moacir");
        //System.out.println("Digite seu nome:");
        //p1.getNome((sc.nextLine());
        p1.setEspecialidade("Professor de POO");
        p1.setIdade(42);
        p1.setSalario(7550.00);
        p1.setSexo("Masculino");
        System.out.println(p1.getNome());
        System.out.println(p1.getEspecialidade());
        System.out.println(p1.getSalario());
        System.out.println(p1.getSexo());
        p1.fazerAniv();
        p1.receberAumento();
        p1.Ensino();
        p2.setNome("Juliana");
        p2.setEspecialidade("Professor de Fisica");
        p2.setIdade(34);
        p2.setSalario(12650.46);
        p2.setSexo("Feminino");
        System.out.println(p2.getNome());
        System.out.println(p2.getEspecialidade());
        System.out.println(p2.getSalario());
        System.out.println(p2.getSexo());
        p2.fazerAniv();
        p2.receberAumento();
        p2.Ensino();
        sc.close();
    }
}
